import { Providers } from "./providers";
import { Amplify } from "aws-amplify";
import awsconfig from "../src/aws-exports";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Amplify.configure({ ...awsconfig, ssr: true });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
